name: Playwright Tests
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest-playwright

    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps firefox chromium

    - name: Run Tests
      run: pytest --browser firefox --browser chromium